name: LCL
channels:
  - conda-forge
  - defaults
dependencies:
  - anndata=0.11.3=pyhd8ed1ab_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - array-api-compat=1.13.0=pyhcf101f3_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - blas=1.0=openblas
  - blosc=1.21.6=h64ef47d_0
  - brotli=1.2.0=hf139dec_1
  - brotli-bin=1.2.0=h8616949_1
  - bzip2=1.0.8=h6c40b1e_6
  - c-ares=1.34.6=hb5e19a0_0
  - c-blosc2=2.12.0=hcf5af9b_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.1=py310h1962661_0
  - cycler=0.12.1=pyhcf101f3_2
  - debugpy=1.8.19=py310haa24e46_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h6d0c2b6_0
  - fonttools=4.61.1=py310hd951482_0
  - freetype=2.13.3=h02243ff_0
  - h5py=3.12.1=py310h6c1bcc5_1
  - hdf5=1.14.5=h80586a8_2
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - jpeg=9e=hb7f2c08_3
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - kiwisolver=1.4.9=py310h355fb9f_2
  - krb5=1.21.3=h37d8d59_0
  - lcms2=2.16=h31d93a5_1
  - legacy-api-wrap=1.5=pyhd8ed1ab_0
  - lerc=4.0.0=hcca01a6_1
  - libbrotlicommon=1.2.0=h8616949_1
  - libbrotlidec=1.2.0=h8616949_1
  - libbrotlienc=1.2.0=h8616949_1
  - libcurl=8.14.1=h1448931_1
  - libcxx=19.1.7=haebbb44_3
  - libdeflate=1.22=h00291cd_0
  - libedit=3.1.20250104=pl5321ha958ccf_0
  - libev=4.33=h10d778d_2
  - libffi=3.4.4=hecd8cb5_1
  - libgfortran=5.0.0=10_4_0_h97931a8_28
  - libgfortran5=11.3.0=h9dfd629_28
  - libnghttp2=1.57.0=h9beae6a_0
  - libopenblas=0.3.29=h3f8574a_0
  - libpng=1.6.39=h6c40b1e_0
  - libsodium=1.0.20=hfdf4475_0
  - libssh2=1.11.1=h3a17b82_0
  - libtiff=4.7.0=h2dfa3ea_0
  - libwebp-base=1.6.0=hb807250_0
  - llvm-openmp=19.1.7=h5048363_2
  - llvmlite=0.44.0=py310hfa5e528_1
  - lz4-c=1.9.4=hf0c8a7f_0
  - lzo=2.10=h4132b18_1002
  - matplotlib=3.9.4=py310h2ec42d9_0
  - matplotlib-base=3.9.4=py310h1671ce3_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - natsort=8.4.0=pyh29332c3_1
  - ncurses=6.5=h923df54_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.4.2=pyh267e887_2
  - numba=0.61.2=py310h2d33a94_0
  - numexpr=2.14.1=py310h4795a84_1
  - numpy=1.26.4=py310hf6dca73_0
  - numpy-base=1.26.4=py310hd8f4981_0
  - openjpeg=2.5.2=h2d09ccc_1
  - openssl=3.6.0=h230baf5_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py310h39ce848_1
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.2=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py310h935ef2f_1
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.1=py310h8bcfd8d_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-cpuinfo=9.0.0=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pynndescent=0.5.13=pyhd8ed1ab_1
  - pyparsing=3.3.1=pyhcf101f3_0
  - pytables=3.10.1=py310h043e903_1
  - python=3.10.18=hc958d9f_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - pyzmq=27.1.0=py310hbbd5e6a_0
  - qhull=2020.2=h3c5361c_5
  - readline=8.3=h49f2429_0
  - scanpy=1.11.5=pyhd8ed1ab_0
  - scikit-learn=1.7.2=py310h4e9a27a_0
  - scipy=1.15.3=py310h97975f9_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - session-info2=0.3=pyhd8ed1ab_0
  - setuptools=78.1.1=py310hecd8cb5_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=hc8b0dd6_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.6=py310h0bce67a_0
  - tbb=2021.8.0=ha357a0b_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=h3a5a201_0
  - tornado=6.5.4=py310h2513d93_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - umap-learn=0.5.11=py310h2ec42d9_0
  - unicodedata2=17.0.0=py310hd2d5e8d_1
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py310hecd8cb5_0
  - xz=5.6.4=h46256e1_1
  - zeromq=4.3.5=h6c33b1e_9
  - zlib=1.2.13=h4b97444_1
  - zlib-ng=2.0.7=h6c40b1e_0
  - zstd=1.5.6=h138b38a_0
  - pip:
    - absl-py==2.3.1
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.13.3
    - aiosignal==1.4.0
    - argparse==1.4.0
    - async-timeout==5.0.1
    - attrs==25.4.0
    - captum==0.8.0
    - filelock==3.20.3
    - frozenlist==1.8.0
    - fsspec==2026.1.0
    - grpcio==1.76.0
    - idna==3.11
    - jinja2==3.1.6
    - lightning-bolts==0.7.0
    - lightning-utilities==0.15.2
    - markdown==3.10
    - markupsafe==3.0.3
    - mpmath==1.3.0
    - multidict==6.7.0
    - multiprocessing-logging==0.3.4
    - propcache==0.4.1
    - protobuf==6.33.4
    - pytorch-lightning==1.9.5
    - pyyaml==6.0.3
    - sympy==1.14.0
    - tensorboard==2.20.0
    - tensorboard-data-server==0.7.2
    - torch==2.2.2
    - torchmetrics==1.8.2
    - torchvision==0.17.2
    - werkzeug==3.1.5
    - yarl==1.22.0
prefix: /opt/anaconda3/envs/LCL
